name: Build and Test

on:
  push:
    branches: [main]
  pull_request:
    branches: [ main ]


jobs:
  build-and-test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.12]
    steps:
    - uses: actions/checkout@v4
      with:
        submodules: true
        fetch-depth: 0
        persist-credentials: false
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v5
      with:
        python-version: ${{ matrix.python-version }}
    - name: Update setuptools and wheel
      run: |
          python -m pip install --upgrade pip setuptools wheel
    - name: Install the package and dependencies
      run: |
          pip install .
    - name: Install the test dependencies
      run: |
          pip install .[test]
    - name: Run tests
      run: |
          pytest